gh-release-make-flags-optional
digitalfabrik/app-toolbelt pull request #13
Opened 2024-04-22 08:52 UTC by f1sh1918

make flags optional

2024-04-22 08:59 UTC, ztefanie requested changes
I get an error, when trying to run this `v0 release create all 1 1 --deliverino-private-key my-key --should-use-predefined-release-notes`

error: option '--should-use-predefined-release-notes <should-use-predefined-release-notes>' argument missing

2024-04-22 09:19 UTC, f1sh1918 commented
> I get an error, when trying to run this `v0 release create all 1 1 --deliverino-private-key my-key --should-use-predefined-release-notes`
> 
> error: option '--should-use-predefined-release-notes ' argument missing

how can you run this without `--owner --repo` and @ztefanie ?

2024-04-23 07:26 UTC, f1sh1918 commented
i pushed new commit @ztefanie thx for the hint

2024-04-24 06:45 UTC, ztefanie commented on src/release/program-github-release.ts
> +    .option('--should-use-predefined-release-notes', 'whether predefined release notes should be used or not. Release notes have to be passed if true.')
```suggestion
    .option('--should-use-predefined-release-notes', 'whether predefined release notes should be used or not. Release notes have to be passed if set. If unset false')
```

2024-04-24 06:46 UTC, ztefanie approved these changes
Just one little comment.

2024-04-24 09:34 UTC, merged